spring:
  application:
    name: your-city-service
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/your_city
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
